Repository backtrace-labs/backtrace-javascript, pull requests merged in 2023-06, with the labels that each got.

#6 Stack trace parser
  package-lock.json
  package.json
  packages/browser/jest.config.js
  packages/browser/package.json
  packages/browser/src/converters/JavaScriptCoreStackTraceConverter.ts
  packages/browser/src/converters/SpiderMonkeyStackTraceConverter.ts
  packages/browser/src/engineDetector.ts
  packages/browser/tests/converters/javascriptCore/javaScriptCoreStackTraceConverterTests.spec.ts
  packages/browser/tests/converters/javascriptCore/javaScriptCoreStackTraceTestCases.ts
  packages/browser/tests/converters/spiderMonkey/spiderMonkeyStackTraceConverterTests.spec.ts
  packages/browser/tests/converters/spiderMonkey/spiderMonkeyStackTraceTestCases.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/data/BacktraceStackTrace.ts
  packages/sdk-core/src/model/data/JavaScriptEngine.ts
  packages/sdk-core/src/modules/converter/BacktraceStackTraceConverter.ts
  packages/sdk-core/src/modules/converter/V8StackTraceConverter.ts
  packages/sdk-core/src/modules/converter/consts/frameNamesConsts.ts
  packages/sdk-core/src/modules/converter/index.ts
  packages/sdk-core/tests/converters/stackTraceConverterTests.spec.ts
  packages/sdk-core/tests/converters/v8stackTraceTestCases.ts
Labels: enhancement

#7 Data submission API
  package-lock.json
  packages/browser/src/BacktraceBrowserRequestHandler.ts
  packages/node/src/BacktraceNodeRequestHandler.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/data/BacktraceData.ts
  packages/sdk-core/src/model/http/BacktraceReportSubmission.ts
  packages/sdk-core/src/model/http/BacktraceRequestHandler.ts
  packages/sdk-core/src/model/http/common/ConnectionError.ts
  packages/sdk-core/src/model/http/index.ts
  packages/sdk-core/src/model/http/model/BacktraceSubmissionResponse.ts
  packages/sdk-core/src/model/http/model/BacktraceSubmissionResult.ts
  packages/sdk-core/src/model/http/model/BacktraceSubmissionStatus.ts
Labels: enhancement

#13 Add support for Node 14.
  .github/workflows/test.yml
  package-lock.json
  package.json
  packages/sdk-core/src/model/report/BacktraceReport.ts
  tsconfig.base.json
Labels: enhancement

#10 Use factory to generate client and send report to Backtrace
  packages/browser/src/BacktraceClient.ts
  packages/browser/src/agentDefinition.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/browser/tests/client/clientTests.spec.ts
  packages/node/src/BacktraceClient.ts
  packages/node/src/agentDefinition.ts
  packages/node/src/builder/BacktraceClientBuilder.ts
  packages/node/tests/client/clientTests.spec.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/builder/BacktraceCoreClientBuilder.ts
  packages/sdk-core/src/builder/SdkOptions.ts
  packages/sdk-core/src/common/IdGenerator.ts
  packages/sdk-core/src/common/TimeHelper.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/data/BacktraceData.ts
  packages/sdk-core/src/model/report/BacktraceReport.ts
  packages/sdk-core/src/modules/data/AttributeAndAnnotationBuilder.ts
  packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts
  packages/sdk-core/tests/client/clientTests.spec.ts
  packages/sdk-core/tests/converters/attributeConverterTests.spec.ts
  packages/sdk-core/tests/mocks/BacktraceTestClient.ts
  packages/sdk-core/tests/report/dataGenerationTests.spec.ts
Labels: enhancement

#14 Browser attributes
  package-lock.json
  packages/browser/package.json
  packages/browser/src/BacktraceClient.ts
  packages/browser/src/attributes/UserAgentAttributeProvider.ts
  packages/browser/src/attributes/UserIdentifierAttributeProvider.ts
  packages/browser/src/attributes/WebsiteAttributeProvider.ts
  packages/browser/src/attributes/WindowAttributeProvider.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/browser/tests/attributes/userIdAttributeProviderTests.spec.ts
  packages/browser/tests/client/clientTests.spec.ts
  packages/node/tests/attributes/machineIdAttributeProviderTests.spec.ts
  packages/sdk-core/src/common/TimeHelper.ts
  packages/sdk-core/tests/client/reportLimitWatcherTests.spec.ts
Labels: enhancement

#15 Always use time in ms instead of sec
  packages/browser/src/attributes/WebsiteAttributeProvider.ts
  packages/sdk-core/src/common/TimeHelper.ts
  packages/sdk-core/src/model/report/BacktraceReport.ts
  packages/sdk-core/src/modules/data/AttributeAndAnnotationBuilder.ts
  packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts
  packages/sdk-core/src/modules/rateLimiter/RateLimitWatcher.ts
  packages/sdk-core/tests/client/reportLimitWatcherTests.spec.ts
  packages/sdk-core/tests/converters/attributeConverterTests.spec.ts
  packages/sdk-core/tests/report/dataGenerationTests.spec.ts
Labels: enhancement

#17 Attachment management
  packages/browser/src/BacktraceBrowserRequestHandler.ts
  packages/browser/src/BacktraceClient.ts
  packages/browser/src/BacktraceConfiguration.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/browser/src/index.ts
  packages/browser/tests/client/clientTests.spec.ts
  packages/node/src/BacktraceClient.ts
  packages/node/src/BacktraceConfiguration.ts
  packages/node/src/BacktraceNodeRequestHandler.ts
  packages/node/src/attachment/BacktraceBufferAttachment.ts
  packages/node/src/attachment/BacktraceFileAttachment.ts
  packages/node/src/attachment/index.ts
  packages/node/src/builder/BacktraceClientBuilder.ts
  packages/node/src/index.ts
  packages/node/tests/client/clientTests.spec.ts
  packages/node/tests/client/mock/sampleFile.txt
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/attachment/BacktraceAttachment.ts
  packages/sdk-core/src/model/attachment/BacktraceStringAttachment.ts
  packages/sdk-core/src/model/attachment/BacktraceUint8ArrayAttachment.ts
  packages/sdk-core/src/model/attachment/index.ts
  packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
  packages/sdk-core/src/model/http/BacktraceReportSubmission.ts
  packages/sdk-core/src/model/http/BacktraceRequestHandler.ts
  packages/sdk-core/src/model/report/BacktraceAttachment.ts
  packages/sdk-core/src/model/report/BacktraceReport.ts
  packages/sdk-core/tests/client/clientTests.spec.ts
  packages/sdk-core/tests/mocks/BacktraceTestClient.ts
Labels: enhancement

#18 Read package information
  packages/node/src/attributes/ApplicationInformationAttributeProvider.ts
  packages/node/src/attributes/index.ts
  packages/node/src/builder/BacktraceClientBuilder.ts
  packages/node/tests/attributes/applicationInformationAttributeProviderTests.spec.ts
Labels: enhancement

#20 Add Webpack to the browser package
  build/common.js
  package-lock.json
  packages/browser/jest.config.js
  packages/browser/jest.setup.js
  packages/browser/package.json
  packages/browser/src/BacktraceBrowserRequestHandler.ts
  packages/browser/src/agentDefinition.ts
  packages/browser/src/attributes/WebsiteAttributeProvider.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/browser/src/converters/JavaScriptCoreStackTraceConverter.ts
  packages/browser/src/converters/SpiderMonkeyStackTraceConverter.ts
  packages/browser/src/engineDetector.ts
  packages/browser/src/index.ts
  packages/browser/webpack.config.js
  tsconfig.json
  tsconfig.packages.json
Labels: enhancement

#21 Add Webpack to the node package
  package-lock.json
  packages/node/jest.config.js
  packages/node/jest.setup.js
  packages/node/package.json
  packages/node/src/BacktraceNodeRequestHandler.ts
  packages/node/src/agentDefinition.ts
  packages/node/src/attachment/index.ts
  packages/node/src/attributes/ProcessStatusAttributeProvider.ts
  packages/node/src/index.ts
  packages/node/webpack.config.js
  tsconfig.json
  tsconfig.packages.json
Labels: enhancement

#8 Add helpers for future sourcemap plugins and CLI.
  package-lock.json
  package.json
  tools/sourcemap-tools/LICENSE
  tools/sourcemap-tools/jest.config.js
  tools/sourcemap-tools/package.json
  tools/sourcemap-tools/src/ContentAppender.ts
  tools/sourcemap-tools/src/DebugIdGenerator.ts
  tools/sourcemap-tools/src/index.ts
  tools/sourcemap-tools/tests/ContentAppender.spec.ts
  tools/sourcemap-tools/tests/DebugIdGenerator.spec.ts
  tools/sourcemap-tools/tsconfig.json
  tsconfig.json
  tsconfig.packages.json
Labels: enhancement

#9 Adds Webpack plugin for injecting debug IDs into sources and sourcemaps.
  package-lock.json
  package.json
  tools/sourcemap-tools/tsconfig.json
  tools/webpack-plugin/LICENSE
  tools/webpack-plugin/jest.config.js
  tools/webpack-plugin/package.json
  tools/webpack-plugin/src/BacktracePlugin.ts
  tools/webpack-plugin/src/BacktraceWebpackSourceGenerator.ts
  tools/webpack-plugin/src/index.ts
  tools/webpack-plugin/tests/__mocks__/TestDebugIdGenerator.ts
  tools/webpack-plugin/tests/e2e/createE2ETest.ts
  tools/webpack-plugin/tests/e2e/helpers.ts
  tools/webpack-plugin/tests/e2e/multiple-input-chunked-output/.gitignore
  tools/webpack-plugin/tests/e2e/multiple-input-chunked-output/input/dependency.ts
  tools/webpack-plugin/tests/e2e/multiple-input-chunked-output/input/entry1.ts
  tools/webpack-plugin/tests/e2e/multiple-input-chunked-output/input/entry2.ts
  tools/webpack-plugin/tests/e2e/multiple-input-chunked-output/multiple-input-chunked-output.spec.ts
  tools/webpack-plugin/tests/e2e/multiple-input-chunked-output/tsconfig.test.json
  tools/webpack-plugin/tests/e2e/multiple-input-multiple-output/.gitignore
  tools/webpack-plugin/tests/e2e/multiple-input-multiple-output/input/dependency.ts
  tools/webpack-plugin/tests/e2e/multiple-input-multiple-output/input/entry1.ts
  tools/webpack-plugin/tests/e2e/multiple-input-multiple-output/input/entry2.ts
  tools/webpack-plugin/tests/e2e/multiple-input-multiple-output/multiple-input-multiple-output.spec.ts
  tools/webpack-plugin/tests/e2e/multiple-input-multiple-output/tsconfig.test.json
  tools/webpack-plugin/tests/e2e/no-sourcemaps/.gitignore
  tools/webpack-plugin/tests/e2e/no-sourcemaps/input/dependency.ts
  tools/webpack-plugin/tests/e2e/no-sourcemaps/input/index.ts
  tools/webpack-plugin/tests/e2e/no-sourcemaps/no-sourcemaps.spec.ts
  tools/webpack-plugin/tests/e2e/no-sourcemaps/tsconfig.test.json
  tools/webpack-plugin/tests/e2e/single-input-single-output/.gitignore
  tools/webpack-plugin/tests/e2e/single-input-single-output/input/dependency.ts
  tools/webpack-plugin/tests/e2e/single-input-single-output/input/index.ts
  tools/webpack-plugin/tests/e2e/single-input-single-output/single-input-single-output.spec.ts
  tools/webpack-plugin/tests/e2e/single-input-single-output/tsconfig.test.json
  tools/webpack-plugin/tests/e2e/tsconfig.test-base.json
  tools/webpack-plugin/tests/e2e/typescript-sourcemaps/.gitignore
  tools/webpack-plugin/tests/e2e/typescript-sourcemaps/input/dependency.ts
  tools/webpack-plugin/tests/e2e/typescript-sourcemaps/input/index.ts
  tools/webpack-plugin/tests/e2e/typescript-sourcemaps/tsconfig.test.json
  tools/webpack-plugin/tests/e2e/typescript-sourcemaps/typescript-sourcemaps.spec.ts
  tools/webpack-plugin/tests/unit/BacktraceWebpackSourceGenerator.spec.ts
  tools/webpack-plugin/tsconfig.json
  tsconfig.json
  tsconfig.packages.json
Labels: enhancement

#22 Add common code for sourcemap uploading.
  package-lock.json
  tools/sourcemap-tools/package.json
  tools/sourcemap-tools/src/SourceMapUploader.ts
  tools/sourcemap-tools/src/index.ts
  tools/sourcemap-tools/tests/SourceMapUploader.spec.ts
  tools/sourcemap-tools/tests/testFiles/sourcemap.js.map
Labels: enhancement

#31 Browser example
  examples/sdk/browser/index.css
  examples/sdk/browser/index.html
  examples/sdk/browser/package-lock.json
  examples/sdk/browser/package.json
  examples/sdk/browser/src/consts.ts
  examples/sdk/browser/src/index.ts
  examples/sdk/browser/tsconfig.json
  examples/sdk/browser/webpack.config.js
Labels: documentation, enhancement, good first issue

#30 Browser adjustements
  examples/sdk/browser/index.css
  examples/sdk/browser/index.html
  examples/sdk/browser/package-lock.json
  examples/sdk/browser/package.json
  examples/sdk/browser/src/consts.ts
  examples/sdk/browser/src/index.ts
  examples/sdk/browser/tsconfig.json
  examples/sdk/browser/webpack.config.js
  packages/browser/src/BacktraceBrowserRequestHandler.ts
  packages/browser/src/attributes/ApplicationInformationAttributeProvider.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
Labels: bug

#28 Add `SourceProcessor` class
  package-lock.json
  tools/sourcemap-tools/package.json
  tools/sourcemap-tools/src/DebugIdGenerator.ts
  tools/sourcemap-tools/src/SourceProcessor.ts
  tools/sourcemap-tools/src/helpers/bytesToUuid.ts
  tools/sourcemap-tools/src/helpers/stringToUuid.ts
  tools/sourcemap-tools/src/index.ts
  tools/sourcemap-tools/tests/SourceProcessor.spec.ts
Labels: enhancement

#29 Use `SourceProcessor` in Webpack
  tools/webpack-plugin/jest.config.js
  tools/webpack-plugin/package.json
  tools/webpack-plugin/src/BacktracePlugin.ts
  tools/webpack-plugin/src/BacktracePluginV4.ts
  tools/webpack-plugin/src/BacktracePluginV5.ts
  tools/webpack-plugin/src/BacktraceWebpackSourceGenerator.ts
  tools/webpack-plugin/src/index.ts
  tools/webpack-plugin/src/models/BacktracePluginOptions.ts
  tools/webpack-plugin/tests/e2e/createE2ETest.ts
  tools/webpack-plugin/tests/e2e/helpers.ts
  tools/webpack-plugin/tests/e2e/no-sourcemaps/no-sourcemaps.spec.ts
  tools/webpack-plugin/tests/unit/BacktraceWebpackSourceGenerator.spec.ts
  tools/webpack-plugin/webpack4.jest.config.js
Labels: enhancement

#34 Submission URL parser
  packages/sdk-core/src/model/http/BacktraceReportSubmission.ts
  packages/sdk-core/src/model/http/SubmissionUrlInformation.ts
  packages/sdk-core/src/model/http/index.ts
  packages/sdk-core/src/modules/metrics/MetricsUrlInformation.ts
  packages/sdk-core/tests/http/submissionUrlGenerationTests.spec.ts
  packages/sdk-core/tests/http/tokenTests.spec.ts
  packages/sdk-core/tests/http/universeTests.spec.ts
Labels: enhancement

#32 Add printing asset stats to Webpack plugin
  package-lock.json
  tools/webpack-plugin/.gitignore
  tools/webpack-plugin/package.json
  tools/webpack-plugin/src/BacktracePlugin.ts
  tools/webpack-plugin/src/helpers/statsPrinter.ts
  tools/webpack-plugin/src/models/AssetStats.ts
  tools/webpack-plugin/webpack.config.js
Labels: enhancement

#36 Feature/metrics
  examples/sdk/browser/index.html
  examples/sdk/browser/src/index.ts
  examples/sdk/node/src/index.ts
  packages/browser/src/BacktraceBrowserSessionProvider.ts
  packages/browser/src/BacktraceClient.ts
  packages/browser/tests/client/clientTests.spec.ts
  packages/browser/tests/metrics/persistentSessionProviderTests.spec.ts
  packages/node/tests/client/clientTests.spec.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/common/DelayHelper.ts
  packages/sdk-core/src/common/TimeHelper.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
  packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
  packages/sdk-core/src/modules/metrics/BacktraceSessionProvider.ts
  packages/sdk-core/src/modules/metrics/MetricsBuilder.ts
  packages/sdk-core/src/modules/metrics/MetricsQueue.ts
  packages/sdk-core/src/modules/metrics/MetricsSubmissionQueue.ts
  packages/sdk-core/src/modules/metrics/MetricsUrlInformation.ts
  packages/sdk-core/src/modules/metrics/SingleSessionProvider.ts
  packages/sdk-core/src/modules/metrics/model/MetricsEvent.ts
  packages/sdk-core/src/modules/metrics/model/SummedEvent.ts
  packages/sdk-core/src/modules/metrics/model/UniqueEvent.ts
  packages/sdk-core/tests/metrics/metricSetupTests.spec.ts
  packages/sdk-core/tests/metrics/mocks/mockSubmissionQueue.ts
  packages/sdk-core/tests/metrics/summedEventTests.spec.ts
  packages/sdk-core/tests/metrics/uniqueEventTests.spec.ts
  packages/sdk-core/tests/mocks/BacktraceTestClient.ts
  packages/sdk-core/tests/mocks/testHttpClient.ts
Labels: enhancement
