Repository backtrace-labs/backtrace-javascript, pull requests merged in 2023-11, with the labels that each got.

#192 cli: version 0.2.1
  package-lock.json
  tools/cli/package.json
  tools/cli/src/sourcemaps/run.ts
Labels: bug, enhancement, release

#193 node: version 0.1.1
  package-lock.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#195 node: fix AlternatingFileWriter crash on high load
  packages/node/src/BacktraceClient.ts
  packages/node/src/breadcrumbs/FileBreadcrumbsStorage.ts
  packages/node/src/builder/BacktraceClientSetup.ts
  packages/node/src/common/AlternatingFileWriter.ts
  packages/node/src/storage/FsNodeFileSystem.ts
  packages/node/src/storage/interfaces/NodeFileSystem.ts
  packages/node/tests/_mocks/fileSystem.ts
  packages/node/tests/common/alternatingFile.spec.ts
  packages/sdk-core/tests/_mocks/fileSystem.ts
Labels: bug

#196 nestjs: version 0.1.1
  package-lock.json
  packages/nestjs/CHANGELOG.md
  packages/nestjs/jest.config.js
  packages/nestjs/package.json
Labels: release

#197 node: version 0.1.2
  package-lock.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#200 node: version 0.1.3
  package-lock.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#201 nestjs: add option to don't throw if BacktraceClient is undefined
  packages/nestjs/src/backtrace.interceptor.ts
Labels: enhancement

#202 electron: version 0.1.0
  package-lock.json
  packages/electron/CHANGELOG.md
  packages/electron/package.json
Labels: release

#194 Hermes react stack trace
  packages/react-native/src/BacktraceClient.ts
  packages/sdk-core/src/modules/converter/V8StackTraceConverter.ts
  packages/sdk-core/tests/converters/stackTraceConverterTests.spec.ts
  packages/sdk-core/tests/converters/v8stackTraceTestCases.ts
Labels: bug

#203 Source map global this
  tools/sourcemap-tools/src/DebugIdGenerator.ts
Labels: enhancement

#198 cli: partial processing
  package-lock.json
  tools/cli/jest.config.js
  tools/cli/package.json
  tools/cli/src/sourcemaps/process.ts
  tools/cli/tests/_files/processed-sourcemaps/entry1.js
  tools/cli/tests/_files/processed-sourcemaps/entry1.js.map
  tools/cli/tests/_files/processed-sourcemaps/entry2.js
  tools/cli/tests/_files/processed-sourcemaps/entry2.js.map
  tools/cli/tests/_files/processed-sources/entry1.js
  tools/cli/tests/_files/processed-sources/entry1.js.map
  tools/cli/tests/_files/processed-sources/entry2.js
  tools/cli/tests/_files/processed-sources/entry2.js.map
  tools/cli/tests/_helpers/testFiles.ts
  tools/cli/tests/setup.ts
  tools/cli/tests/sourcemaps/process.spec.ts
  tools/sourcemap-tools/src/DebugIdGenerator.ts
  tools/sourcemap-tools/src/SourceProcessor.ts
  tools/sourcemap-tools/tests/SourceProcessor.spec.ts
Labels: enhancement

#199 cli: support tuple paths
  tools/cli/src/helpers/common.ts
  tools/cli/src/helpers/errorBehavior.ts
  tools/cli/src/helpers/find.ts
  tools/cli/src/helpers/logs.ts
  tools/cli/src/models/Asset.ts
  tools/cli/src/sourcemaps/add-sources.ts
  tools/cli/src/sourcemaps/process.ts
  tools/cli/src/sourcemaps/run.ts
  tools/cli/src/sourcemaps/upload.ts
  tools/cli/tests/_files/not-linked-different-name-sourcemaps/entry1.js
  tools/cli/tests/_files/not-linked-different-name-sourcemaps/entry2.js
  tools/cli/tests/_files/not-linked-different-name-sourcemaps/sourcemap1.js.map
  tools/cli/tests/_files/not-linked-different-name-sourcemaps/sourcemap2.js.map
  tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/entry1.js
  tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/entry2.js
  tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/sourcemap1.js.map
  tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/sourcemap2.js.map
  tools/cli/tests/_helpers/testFiles.ts
  tools/cli/tests/sourcemaps/add-sources.spec.ts
  tools/cli/tests/sourcemaps/process.spec.ts
  tools/cli/tests/sourcemaps/run.spec.ts
  tools/cli/tests/sourcemaps/upload.spec.ts
  tools/sourcemap-tools/src/SourceProcessor.ts
  tools/sourcemap-tools/src/helpers/common.ts
Labels: enhancement

#204 node: fix native reports not sending after startup
  packages/node/src/common/AlternatingFileWriter.ts
  packages/node/tests/common/alternatingFile.spec.ts
Labels: bug

#205 browser: add middleware modes to redux middleware, move JSON action to attributes
  packages/browser/src/redux/BacktraceReduxMiddleware.ts
  packages/browser/tests/redux/backtraceReduxMiddlewareTests.spec.ts
Labels: enhancement

#208 react-native: managed breadcrumb support
  packages/react-native/src/breadcrumbs/events/AppStateBreadcrumbSubscriber.ts
  packages/react-native/src/breadcrumbs/events/DimensionChangeBreadcrumbSubscriber.ts
  packages/react-native/src/breadcrumbs/events/WebRequestEventSubscriber.ts
  packages/react-native/src/builder/BacktraceClientBuilder.ts
Labels: enhancement

#210 sourcemap-tools: version 0.2.1
  package-lock.json
  tools/sourcemap-tools/package.json
Labels: release

#211 cli: version 0.3.0
  package-lock.json
  tools/cli/CHANGELOG.md
  tools/cli/package.json
Labels: release

#212 sdk-core: version 0.2.0
  package-lock.json
  packages/browser/package.json
  packages/node/package.json
  packages/react-native/package.json
  packages/react/package.json
  packages/sdk-core/CHANGELOG.md
  packages/sdk-core/package.json
Labels: release

#213 node: version 0.2.0
  package-lock.json
  packages/electron/package.json
  packages/nestjs/package.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#214 browser: version 0.2.0
  package-lock.json
  packages/browser/CHANGELOG.md
  packages/browser/package.json
  packages/react/package.json
Labels: release

#215 react: version 0.2.0
  package-lock.json
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: release

#216 electron: version 0.2.0
  package-lock.json
  packages/electron/CHANGELOG.md
  packages/electron/package.json
Labels: release

#217 nestjs: version 0.2.0
  package-lock.json
  packages/nestjs/CHANGELOG.md
  packages/nestjs/package.json
Labels: release
