Repository backtrace-labs/backtrace-javascript, pull requests merged in 2023-08, with the labels that each got.

#52 Breadcrumbs support
  packages/browser/tests/client/clientTests.spec.ts
  packages/node/tests/client/clientTests.spec.ts
  packages/node/tests/common/nodeOptionReaderTests.spec.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/dataStructures/OverwritingArray.ts
  packages/sdk-core/src/dataStructures/OverwritingArrayIterator.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
  packages/sdk-core/src/modules/breadcrumbs/BacktraceBreadcrumbs.ts
  packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
  packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsSetup.ts
  packages/sdk-core/src/modules/breadcrumbs/events/BreadcrurmbsEventSubscriber.ts
  packages/sdk-core/src/modules/breadcrumbs/events/ConsoleEventSubscriber.ts
  packages/sdk-core/src/modules/breadcrumbs/index.ts
  packages/sdk-core/src/modules/breadcrumbs/model/Breadcrumb.ts
  packages/sdk-core/src/modules/breadcrumbs/model/BreadcrumbLogLevel.ts
  packages/sdk-core/src/modules/breadcrumbs/model/BreadcrumbType.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/BreadcrumbsStorage.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsFilteringOptionsTests.spec.ts
  packages/sdk-core/tests/client/clientTests.spec.ts
Labels: enhancement

#53 sourcemap tools: fix doesSourceMapHaveSources with undefined sources
  tools/sourcemap-tools/src/SourceProcessor.ts
Labels: bug

#54 sourcemap tools: add common code for bundler plugins and CLI
  tools/sourcemap-tools/src/SourceProcessor.ts
  tools/sourcemap-tools/src/commands/archiveSourceMaps.ts
  tools/sourcemap-tools/src/commands/index.ts
  tools/sourcemap-tools/src/commands/processAndUploadAssetsCommand.ts
  tools/sourcemap-tools/src/commands/processAsset.ts
  tools/sourcemap-tools/src/commands/uploadArchive.ts
  tools/sourcemap-tools/src/commands/writeAsset.ts
  tools/sourcemap-tools/src/helpers/common.ts
  tools/sourcemap-tools/src/helpers/match.ts
  tools/sourcemap-tools/src/index.ts
  tools/sourcemap-tools/src/models/Asset.ts
  tools/sourcemap-tools/src/models/AsyncResult.ts
  tools/sourcemap-tools/src/models/ProcessAssetResult.ts
Labels: enhancement

#58 sourcemap tools: add stripping of sourceContent by default
  .github/workflows/test.yml
  package-lock.json
  tools/cli/src/sourcemaps/upload.ts
  tools/sourcemap-tools/src/commands/archiveSourceMaps.ts
  tools/sourcemap-tools/src/commands/index.ts
  tools/sourcemap-tools/src/commands/loadSourceMaps.ts
  tools/sourcemap-tools/src/commands/processAndUploadAssetsCommand.ts
  tools/sourcemap-tools/src/index.ts
  tools/sourcemap-tools/src/models/Asset.ts
  tools/webpack-plugin/src/BacktracePlugin.ts
  tools/webpack-plugin/src/index.ts
  tools/webpack-plugin/src/models/BacktracePluginOptions.ts
Labels: enhancement

#59 cli: add stripping sourcesContent by default
  tools/cli/src/sourcemaps/upload.ts
Labels: enhancement

#61 vite plugin based on rollup
  package-lock.json
  tools/vite-plugin/.gitignore
  tools/vite-plugin/LICENSE
  tools/vite-plugin/package.json
  tools/vite-plugin/src/index.ts
  tools/vite-plugin/tsconfig.build.json
  tools/vite-plugin/tsconfig.json
  tools/vite-plugin/vite.config.js
Labels: enhancement

#62 Database support
  examples/sdk/node/.gitignore
  examples/sdk/node/src/index.ts
  packages/node/src/BacktraceClient.ts
  packages/node/src/attachment/BacktraceFileAttachment.ts
  packages/node/src/database/BacktraceDatabaseFileRecord.ts
  packages/node/src/database/BacktraceDatabaseFileStorageProvider.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/configuration/BacktraceDatabaseConfiguration.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/src/modules/database/BacktraceDatabaseContext.ts
  packages/sdk-core/src/modules/database/BacktraceDatabaseStorageProvider.ts
  packages/sdk-core/src/modules/database/index.ts
  packages/sdk-core/src/modules/database/model/BacktraceDatabaseRecord.ts
  packages/sdk-core/tests/client/clientCallbacksTests.spec.ts
  packages/sdk-core/tests/database/databaseContextMemoryStorageTests.spec.ts
  packages/sdk-core/tests/database/databaseContextValidationTests.spec.ts
  packages/sdk-core/tests/database/databaseRecordBatchTests.spec.ts
  packages/sdk-core/tests/database/databaseSetupTests.spec.ts
  packages/sdk-core/tests/database/databaseStorageFlowTests.spec.ts
  packages/sdk-core/tests/mocks/BacktraceTestClient.ts
  packages/sdk-core/tests/mocks/testStorageProvider.ts
Labels: enhancement

#64 Browser breadcrumbs support
  packages/browser/src/BacktraceClient.ts
  packages/browser/src/breadcrumbs/DocumentEventSubscriber.ts
  packages/browser/src/breadcrumbs/HistoryEventSubscriber.ts
  packages/browser/src/breadcrumbs/WebRequestEventSubscriber.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/react/src/builder/BacktraceReactClientBuilder.ts
  packages/sdk-core/src/modules/breadcrumbs/events/ConsoleEventSubscriber.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts
Labels: enhancement

#67 cli: quality of life improvements
  package-lock.json
  tools/cli/package.json
  tools/cli/src/commands/Command.ts
  tools/cli/src/helpers/jsonc.ts
  tools/cli/src/helpers/normalizePaths.ts
  tools/cli/src/helpers/version.ts
  tools/cli/src/index.ts
  tools/cli/src/options/loadOptions.ts
  tools/cli/src/options/models/CliOptions.ts
  tools/cli/src/sourcemaps/add-sources.ts
  tools/cli/src/sourcemaps/process.ts
  tools/cli/src/sourcemaps/upload.ts
Labels: enhancement

#68 cli: add subdomain and token options to upload
  tools/cli/src/sourcemaps/upload.ts
Labels: enhancement

#70 Database send operations
  packages/node/src/database/BacktraceDatabaseFileRecord.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/src/modules/database/model/BacktraceDatabaseRecord.ts
  packages/sdk-core/tests/database/databaseContextMemoryStorageTests.spec.ts
  packages/sdk-core/tests/database/databaseSendTests.spec.ts
  packages/sdk-core/tests/mocks/testStorageProvider.ts
Labels: enhancement

#71 Release setup
  packages/browser/.npmignore
  packages/browser/package.json
  packages/node/.npmignore
  packages/node/package.json
  packages/react/.npmignore
  packages/react/package.json
  tools/cli/.npmignore
  tools/cli/package.json
  tools/rollup-plugin/.npmignore
  tools/rollup-plugin/package.json
  tools/vite-plugin/.npmignore
  tools/vite-plugin/package.json
  tools/webpack-plugin/.npmignore
  tools/webpack-plugin/package.json
Labels: enhancement

#75 Fix possible circular reference in the annotation object
  packages/browser/src/BacktraceBrowserRequestHandler.ts
  packages/node/src/BacktraceNodeRequestHandler.ts
  packages/node/src/database/BacktraceDatabaseFileStorageProvider.ts
  packages/sdk-core/src/common/jsonEscaper.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/http/BacktraceReportSubmission.ts
  packages/sdk-core/src/model/http/BacktraceRequestHandler.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts
  packages/sdk-core/src/modules/metrics/MetricsSubmissionQueue.ts
  packages/sdk-core/tests/client/clientCallbacksTests.spec.ts
  packages/sdk-core/tests/client/clientTests.spec.ts
  packages/sdk-core/tests/http/dataSerializationTests.spec.ts
  tools/sourcemap-tools/tests/DebugIdGenerator.spec.ts
Labels: bug

#78 Allow to use only one client via user-friendly API
  packages/browser/src/BacktraceClient.ts
  packages/node/src/BacktraceClient.ts
  packages/react/src/BacktraceClient.ts
  packages/react/src/ErrorBoundary.tsx
  packages/sdk-core/src/BacktraceCoreClient.ts
Labels: enhancement

#80 Lazy load debug ids
  packages/sdk-core/src/sourcemaps/DebugIdProvider.ts
Labels: bug, enhancement

#79 Release files
  .npmrc
  package-lock.json
  packages/node/package.json
  packages/sdk-core/package.json
Labels: enhancement

#81 Package export
  examples/sdk/browser/package.json
  examples/sdk/node/package.json
  examples/sdk/node/src/index.ts
  examples/sdk/react/package-lock.json
  examples/sdk/react/package.json
  examples/sdk/react/src/App.tsx
  package-lock.json
  package.json
  packages/browser/package.json
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/browser/src/index.ts
  packages/node/src/BacktraceClient.ts
  packages/node/src/builder/BacktraceClientBuilder.ts
  packages/node/src/index.ts
  packages/react/package.json
  packages/react/src/builder/BacktraceReactClientBuilder.ts
  packages/react/src/index.ts
  packages/sdk-core/src/builder/BacktraceCoreClientBuilder.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/data/index.ts
Labels: bug

#82 Breadcrumb interceptor
  packages/browser/src/index.ts
  packages/node/src/index.ts
  packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
  packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
  packages/sdk-core/src/modules/breadcrumbs/index.ts
  packages/sdk-core/src/modules/breadcrumbs/model/RawBreadcrumb.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/BreadcrumbsStorage.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsInterceptorTests.spec.ts
Labels: enhancement

#87 Browser
  packages/browser/README.md
  packages/react/README.md
Labels: documentation

#89 Fallback to default log function if the util function is not available
  packages/sdk-core/src/common/textFormatter.ts
  packages/sdk-core/src/modules/breadcrumbs/events/ConsoleEventSubscriber.ts
Labels: bug

#88 Detect missing information about the agent and fallback to the default
  packages/browser/src/engineDetector.ts
Labels: bug

#92 Source map tools README
  tools/sourcemap-tools/README.md
Labels: documentation

#91 SDK Core README
  packages/sdk-core/README.md
Labels: documentation

#96 Fit 'n finish on node readme
  examples/sdk/node/src/index.ts
  packages/node/README.md
  packages/node/src/BacktraceClient.ts
  packages/node/src/database/BacktraceDatabaseFileStorageProvider.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/model/configuration/BacktraceDatabaseConfiguration.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/tests/database/databaseContextMemoryStorageTests.spec.ts
  packages/sdk-core/tests/database/databaseContextValidationTests.spec.ts
  packages/sdk-core/tests/database/databaseRecordBatchTests.spec.ts
  packages/sdk-core/tests/database/databaseSendTests.spec.ts
  packages/sdk-core/tests/database/databaseSetupTests.spec.ts
  packages/sdk-core/tests/database/databaseStorageFlowTests.spec.ts
Labels: documentation

#93 Backtrace node readme
  examples/sdk/node/src/index.ts
  packages/node/README.md
  packages/node/src/BacktraceClient.ts
  packages/node/src/database/BacktraceDatabaseFileStorageProvider.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/model/configuration/BacktraceDatabaseConfiguration.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/tests/database/databaseContextMemoryStorageTests.spec.ts
  packages/sdk-core/tests/database/databaseContextValidationTests.spec.ts
  packages/sdk-core/tests/database/databaseRecordBatchTests.spec.ts
  packages/sdk-core/tests/database/databaseSendTests.spec.ts
  packages/sdk-core/tests/database/databaseSetupTests.spec.ts
  packages/sdk-core/tests/database/databaseStorageFlowTests.spec.ts
Labels: documentation

#94 Client dispose
  packages/browser/src/BacktraceClient.ts
  packages/node/src/BacktraceClient.ts
  packages/node/tests/client/disposeTests.spec.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
Labels: enhancement

#100 Client docs update
  packages/browser/README.md
  packages/node/README.md
  packages/react/README.md
Labels: documentation

#99 Bin starting path
  packages/node/src/attributes/ApplicationInformationAttributeProvider.ts
  packages/node/tests/attributes/applicationInformationAttributeProviderTests.spec.ts
Labels: bug

#103 NodeJS version update
  package-lock.json
  packages/node/package.json
Labels: enhancement

#104 Browser update 0.0.2
  package-lock.json
  packages/browser/package.json
Labels: enhancement

#105 React update 0.0.2
  package-lock.json
  packages/react/package.json
Labels: enhancement

#101 cli: do not filter out direct glob paths
  tools/cli/src/helpers/find.ts
  tools/cli/src/sourcemaps/add-sources.ts
  tools/cli/src/sourcemaps/process.ts
  tools/cli/src/sourcemaps/upload.ts
Labels: enhancement

#102 cli: fix sourcemap upload issues
  package-lock.json
  tools/cli/src/sourcemaps/upload.ts
  tools/rollup-plugin/src/index.ts
  tools/sourcemap-tools/package.json
  tools/sourcemap-tools/src/SymbolUploader.ts
  tools/sourcemap-tools/src/ZipArchive.ts
  tools/sourcemap-tools/src/commands/archiveSourceMaps.ts
  tools/sourcemap-tools/src/commands/processAndUploadAssetsCommand.ts
  tools/sourcemap-tools/src/helpers/common.ts
  tools/sourcemap-tools/tests/ZipArchive.spec.ts
  tools/webpack-plugin/src/BacktracePlugin.ts
Labels: bug

#106 sdk-core: fix skipping stack frame with message reports
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/modules/converter/V8StackTraceConverter.ts
Labels: bug

#110 add deferred user attributes
  packages/browser/README.md
  packages/browser/src/attributes/UserIdentifierAttributeProvider.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/browser/tests/attributes/userIdAttributeProviderTests.spec.ts
  packages/node/README.md
  packages/node/src/attributes/ApplicationInformationAttributeProvider.ts
  packages/node/src/builder/BacktraceClientBuilder.ts
  packages/node/tests/attributes/applicationInformationAttributeProviderTests.spec.ts
  packages/react/README.md
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
  packages/sdk-core/src/modules/attribute/AttributeManager.ts
  packages/sdk-core/src/modules/attribute/ClientAttributeProvider.ts
  packages/sdk-core/src/modules/attribute/UserAttributeProvider.ts
  packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts
  packages/sdk-core/tests/attributes/attributeManager.spec.ts
  packages/sdk-core/tests/client/attributesTests.spec.ts
  packages/sdk-core/tests/http/dataSerializationTests.spec.ts
  packages/sdk-core/tests/metrics/summedEventTests.spec.ts
  packages/sdk-core/tests/metrics/uniqueEventTests.spec.ts
  packages/sdk-core/tests/report/dataGenerationTests.spec.ts
Labels: enhancement

#114 SDK-core 0.0.3 release
  package-lock.json
  packages/sdk-core/package.json
Labels: enhancement

#108 browser: version 0.0.3, add dependency for sdk-core package
  package-lock.json
  packages/browser/package.json
Labels: enhancement

#109 react: version 0.0.3
  package-lock.json
  packages/react/package.json
  packages/react/webpack.config.js
Labels: enhancement
