Repository backtrace-labs/backtrace-javascript, pull requests merged in 2023-10, with the labels that each got.

#150 node: breadcrumbs from previous session in database
  packages/node/src/BacktraceClient.ts
  packages/node/src/breadcrumbs/FileBreadcrumbsStorage.ts
  packages/node/src/common/AlternatingFileWriter.ts
  packages/node/tests/.gitignore
  packages/node/tests/common/alternatingFile.spec.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/model/configuration/BacktraceDatabaseConfiguration.ts
  packages/sdk-core/src/modules/BacktraceModule.ts
  packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
  packages/sdk-core/src/modules/breadcrumbs/index.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/BreadcrumbsStorage.ts
  packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/src/modules/storage/SessionFiles.ts
  packages/sdk-core/src/modules/storage/index.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsFilteringOptionsTests.spec.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsInterceptorTests.spec.ts
  packages/sdk-core/tests/storage/SessionFiles.spec.ts
Labels: enhancement

#152 node: attributes from previous session in native crashes
  examples/sdk/node/src/index.ts
  packages/node/src/BacktraceClient.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/events/AttributeEvents.ts
  packages/sdk-core/src/index.ts
  packages/sdk-core/src/modules/BacktraceModule.ts
  packages/sdk-core/src/modules/BacktraceModules.ts
  packages/sdk-core/src/modules/attribute/AttributeManager.ts
  packages/sdk-core/src/modules/attribute/FileAttributeManager.ts
  packages/sdk-core/src/modules/attribute/index.ts
Labels: enhancement

#154 Error event fallback if the error object is not available
  packages/browser/src/BacktraceClient.ts
Labels: enhancement

#153 Do not use unsupported URL API in the react-native API
  packages/sdk-core/src/model/http/SubmissionUrlInformation.ts
Labels: bug

#151 add NestJS library for handling NestJS errors
  build/common.js
  package-lock.json
  package.json
  packages/nestjs/.npmignore
  packages/nestjs/LICENSE
  packages/nestjs/README.md
  packages/nestjs/jest.config.js
  packages/nestjs/jest.setup.js
  packages/nestjs/package.json
  packages/nestjs/src/backtrace.interceptor.ts
  packages/nestjs/src/backtrace.module.ts
  packages/nestjs/src/index.ts
  packages/nestjs/tests/backtrace.interceptor.spec.ts
  packages/nestjs/tests/backtrace.module.spec.ts
  packages/nestjs/tests/e2e.spec.ts
  packages/nestjs/tsconfig.build.json
  packages/nestjs/tsconfig.json
  packages/nestjs/webpack.config.js
  packages/node/src/index.ts
  packages/sdk-core/src/builder/BacktraceCoreClientBuilder.ts
Labels: enhancement

#162 add methods to BacktraceBreadcrumbs interface and limit BacktraceManager visibility
  packages/browser/src/breadcrumbs/DocumentEventSubscriber.ts
  packages/browser/src/breadcrumbs/HistoryEventSubscriber.ts
  packages/browser/src/breadcrumbs/WebRequestEventSubscriber.ts
  packages/sdk-core/src/modules/breadcrumbs/BacktraceBreadcrumbs.ts
  packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
  packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsSetup.ts
  packages/sdk-core/src/modules/breadcrumbs/events/BreadcrumbsEventSubscriber.ts
  packages/sdk-core/src/modules/breadcrumbs/events/BreadcrurmbsEventSubscriber.ts
  packages/sdk-core/src/modules/breadcrumbs/events/ConsoleEventSubscriber.ts
  packages/sdk-core/src/modules/breadcrumbs/index.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsFilteringOptionsTests.spec.ts
  packages/sdk-core/tests/breadcrumbs/breadcrumbsInterceptorTests.spec.ts
Labels: enhancement

#165 node: Add breadcrumb attribute to the file
  packages/node/src/breadcrumbs/FileBreadcrumbsStorage.ts
Labels: bug

#163 sync versions script
  package-lock.json
  package.json
  scripts/syncVersions.ts
Labels: enhancement

#173 sdk-core, browser, node, react, react-native: builder changes
  packages/browser/src/BacktraceClient.ts
  packages/browser/src/builder/BacktraceClientBuilder.ts
  packages/browser/src/builder/BacktraceClientSetup.ts
  packages/browser/src/converters/getStackTraceConverter.ts
  packages/browser/src/index.ts
  packages/node/src/BacktraceClient.ts
  packages/node/src/BacktraceConfiguration.ts
  packages/node/src/attachment/transformAttachments.ts
  packages/node/src/builder/BacktraceClientBuilder.ts
  packages/node/src/builder/BacktraceClientSetup.ts
  packages/react-native/src/BacktraceClient.ts
  packages/react-native/src/BacktraceClientBuilder.ts
  packages/react-native/src/builder/BacktraceClientBuilder.ts
  packages/react-native/src/builder/BacktraceClientSetup.ts
  packages/react-native/src/index.ts
  packages/react/src/BacktraceClient.ts
  packages/react/src/builder/BacktraceReactClientBuilder.ts
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/builder/BacktraceCoreClientBuilder.ts
  packages/sdk-core/src/builder/CoreClientSetup.ts
  packages/sdk-core/src/index.ts
Labels: enhancement

#179 cli: test and upload improvements
  tools/cli/src/sourcemaps/run.ts
  tools/cli/src/sourcemaps/upload.ts
  tools/sourcemap-tools/src/ZipArchive.ts
  tools/sourcemap-tools/src/commands/loadSourceMaps.ts
  tools/sourcemap-tools/src/commands/uploadArchive.ts
  tools/sourcemap-tools/tests/ZipArchive.spec.ts
Labels: bug, enhancement

#181 sdk-core: version 0.0.7
  package-lock.json
  packages/sdk-core/CHANGELOG.md
  packages/sdk-core/package.json
Labels: release

#164 react-native: android database support
  .gitignore
  examples/sdk/reactNative/index.js
  package-lock.json
  packages/react-native/android/gradle/wrapper/gradle-wrapper.jar
  packages/react-native/android/gradle/wrapper/gradle-wrapper.properties
  packages/react-native/android/gradlew
  packages/react-native/android/gradlew.bat
  packages/react-native/android/src/main/java/backtrace/library/BacktraceDirectoryProvider.java
  packages/react-native/android/src/main/java/backtrace/library/BacktraceFileSystemProvider.java
  packages/react-native/android/src/main/java/backtrace/library/BacktraceReactNative.java
  packages/react-native/android/src/main/java/backtrace/library/ReactNativePackage.java
  packages/react-native/android/src/main/java/backtrace/library/StreamWriter.java
  packages/react-native/src/BacktraceClient.ts
  packages/react-native/src/attachment/BacktraceFileAttachment.ts
  packages/react-native/src/attachment/index.ts
  packages/react-native/src/breadcrumbs/AlternatingFileWriter.ts
  packages/react-native/src/breadcrumbs/FileBreadcrumbsStorage.ts
  packages/react-native/src/builder/BacktraceClientBuilder.ts
  packages/react-native/src/crashReporter/CrashReporter.ts
  packages/react-native/src/index.ts
  packages/react-native/src/storage/FileSystem.ts
  packages/react-native/src/storage/ReactNativeDirectoryProvider.ts
  packages/react-native/src/storage/ReactNativeFileProvider.ts
  packages/react-native/src/storage/ReactNativeFileSystem.ts
  packages/react-native/src/storage/StreamWriter.ts
  packages/react-native/src/storage/index.ts
Labels: enhancement

#174 clI: search sourcemaps in directory specified by sourceMappingURL
  tools/cli/src/helpers/common.ts
  tools/cli/tests/_files/directory-linked-sourcemaps/dir/entry2.js.map
  tools/cli/tests/_files/directory-linked-sourcemaps/entry1.js
  tools/cli/tests/_files/directory-linked-sourcemaps/entry1.js.map
  tools/cli/tests/_files/directory-linked-sourcemaps/entry2.js
  tools/cli/tests/_files/processed-directory-linked-sourcemaps/dir/entry2.js.map
  tools/cli/tests/_files/processed-directory-linked-sourcemaps/entry1.js
  tools/cli/tests/_files/processed-directory-linked-sourcemaps/entry1.js.map
  tools/cli/tests/_files/processed-directory-linked-sourcemaps/entry2.js
  tools/cli/tests/_helpers/testFiles.ts
  tools/cli/tests/sourcemaps/add-sources.spec.ts
  tools/cli/tests/sourcemaps/process.spec.ts
  tools/cli/tests/sourcemaps/run.spec.ts
  tools/cli/tests/sourcemaps/upload.spec.ts
  tools/sourcemap-tools/src/SourceProcessor.ts
  tools/sourcemap-tools/src/helpers/common.ts
  tools/sourcemap-tools/src/helpers/flow.ts
Labels: enhancement

#172 react, browser: add changelogs
  packages/browser/CHANGELOG.md
  packages/react/CHANGELOG.md
Labels: documentation

#177 electron example: add an example for using Electron SDK
  .vscode/launch.json
  examples/sdk/electron/.gitignore
  examples/sdk/electron/assets/index.css
  examples/sdk/electron/assets/index.html
  examples/sdk/electron/package-lock.json
  examples/sdk/electron/package.json
  examples/sdk/electron/src/common/MainApi.ts
  examples/sdk/electron/src/main/consts.ts
  examples/sdk/electron/src/main/index.ts
  examples/sdk/electron/src/main/preload.ts
  examples/sdk/electron/src/renderer/index.ts
  examples/sdk/electron/tsconfig.json
  examples/sdk/electron/tsconfig.main.json
  examples/sdk/electron/tsconfig.renderer.json
  examples/sdk/electron/webpack.config.js
Labels: enhancement

#185 electron: add docs and README
  packages/electron/README.md
  packages/electron/src/renderer/addBacktraceElectron.ts
  packages/electron/src/renderer/common.ts
  packages/electron/src/renderer/ipc/getIpcRpc.ts
  packages/electron/src/renderer/ipc/getIpcTransport.ts
Labels: documentation, enhancement

#188 electron: add additional attributes to main crashes
  packages/electron/src/main/BacktraceClient.ts
  packages/electron/src/main/attributes/AllWindowsAttributeProvider.ts
  packages/electron/src/main/attributes/NetAttributeProvider.ts
  packages/electron/src/main/attributes/ScreenAttributeProvider.ts
  packages/electron/src/main/attributes/WindowAttributeProvider.ts
  packages/electron/src/main/attributes/helpers/attributes.ts
  packages/electron/src/main/builder/BacktraceClientBuilder.ts
  packages/electron/src/main/modules/BacktraceMainElectronModule.ts
Labels: enhancement

#182 scripts: add scripts for making releases
  package-lock.json
  package.json
  scripts/README.md
  scripts/common/commands.ts
  scripts/common/git.ts
  scripts/common/output.ts
  scripts/common/packageJson.ts
  scripts/common/transaction.ts
  scripts/gitRelease.ts
  scripts/release.ts
  scripts/syncVersions.ts
  tsconfig.json
Labels: enhancement

#189 electron: add breadcrumbs
  packages/electron/src/main/attributes/helpers/attributes.ts
  packages/electron/src/main/breadcrumbs/WindowEventSubscriber.ts
  packages/electron/src/main/builder/BacktraceClientBuilder.ts
Labels: enhancement
