Repository backtrace-labs/backtrace-javascript, pull requests merged in 2024-12, with the labels that each got.

#322 node: fix invalid error handler in fileChunkSink
  packages/node/src/streams/fileChunkSink.ts
Labels: bug

#323 node: version 0.6.2
  package-lock.json
  packages/electron/package.json
  packages/nestjs/package.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#292 react-native example: update to react-native 0.75.3 boilerplate code
  .vscode/launch.json
  examples/sdk/reactNative/.gitignore
  examples/sdk/reactNative/Gemfile
  examples/sdk/reactNative/Gemfile.lock
  examples/sdk/reactNative/android/app/build.gradle
  examples/sdk/reactNative/android/app/src/debug/AndroidManifest.xml
  examples/sdk/reactNative/android/app/src/debug/java/com/reactnative/ReactNativeFlipper.java
  examples/sdk/reactNative/android/app/src/main/AndroidManifest.xml
  examples/sdk/reactNative/android/app/src/main/java/com/reactnative/BacktraceDemoPackage.java
  examples/sdk/reactNative/android/app/src/main/java/com/reactnative/ErrorGenerator.java
  examples/sdk/reactNative/android/app/src/main/java/com/reactnative/MainApplication.java
  examples/sdk/reactNative/android/app/src/main/res/drawable/rn_edit_text_material.xml
  examples/sdk/reactNative/android/app/src/main/res/xml/network_security_config.xml
  examples/sdk/reactNative/android/app/src/release/java/com/reactnative/ReactNativeFlipper.java
  examples/sdk/reactNative/android/build.gradle
  examples/sdk/reactNative/android/gradle.properties
  examples/sdk/reactNative/android/gradle/wrapper/gradle-wrapper.jar
  examples/sdk/reactNative/android/gradle/wrapper/gradle-wrapper.properties
  examples/sdk/reactNative/android/gradlew
  examples/sdk/reactNative/android/gradlew.bat
  examples/sdk/reactNative/android/settings.gradle
  examples/sdk/reactNative/babel.config.js
  examples/sdk/reactNative/ios/Podfile
  examples/sdk/reactNative/ios/Podfile.lock
  examples/sdk/reactNative/ios/reactNative.xcodeproj/project.pbxproj
  examples/sdk/reactNative/ios/reactNative.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  examples/sdk/reactNative/ios/reactNative/AppDelegate.mm
  examples/sdk/reactNative/ios/reactNative/Info.plist
  examples/sdk/reactNative/ios/reactNative/PrivacyInfo.xcprivacy
  examples/sdk/reactNative/metro.config.js
  examples/sdk/reactNative/package-lock.json
  examples/sdk/reactNative/package.json
  examples/sdk/reactNative/tsconfig.json
  package-lock.json
  package.json
Labels: enhancement

#324 react-native example: fix sourcemap support on iOS
  examples/sdk/reactNative/ios-hermesc.sh
  examples/sdk/reactNative/ios-sourcemaps.sh
  examples/sdk/reactNative/ios/reactNative.xcodeproj/project.pbxproj
  examples/sdk/reactNative/ios/reactNative.xcodeproj/xcshareddata/xcschemes/reactNative.xcscheme
  examples/sdk/reactNative/package-lock.json
  examples/sdk/reactNative/package.json
Labels: bug

#326 smoketest: Downgrade react types in smoketests to the version in the sdk
  smoketests/packages/react-ts-esm/package.json
Labels: bug

#325 react-native: Enable native functions for Bridgeless react-native setup
  packages/react-native/src/builder/BacktraceClientBuilder.ts
  packages/react-native/src/common/DebuggerHelper.ts
  packages/react-native/src/crashReporter/CrashReporter.ts
  packages/react-native/src/handlers/android/AndroidUnhandledExceptionHandler.ts
Labels: bug, enhancement

#329 webpack-plugin: fix e2e tests (NFC)
  tools/webpack-plugin/src/index.ts
  tools/webpack-plugin/tests/__mocks__/TestDebugIdGenerator.ts
  tools/webpack-plugin/tests/e2e/createE2ETest.ts
  tools/webpack-plugin/tests/e2e/helpers.ts
  tools/webpack-plugin/tsconfig.build.json
  tools/webpack-plugin/tsconfig.json
Labels: bug

#330 electron: fix potential loop with gpu-info-update
  packages/electron/src/main/attributes/GpuAttributeProvider.ts
Labels: bug

#331 electron: version 0.6.2
  package-lock.json
  packages/electron/CHANGELOG.md
  packages/electron/package.json
Labels: release
