Repository backtrace-labs/backtrace-javascript, pull requests merged in 2024-06, with the labels that each got.

#250 node: replace native-reg with call to reg query
  package-lock.json
  packages/node/package.json
  packages/node/src/attributes/MachineIdentitfierAttributeProvider.ts
Labels: bug, enhancement

#252 Apply default formatting proposed by prettier latest
  examples/sdk/node/package.json
  package-lock.json
  package.json
  packages/browser/package.json
  packages/electron/package.json
  packages/electron/src/main/attributes/WindowAttributeProvider.ts
  packages/electron/src/main/ipc/ReadableIpcStream.ts
  packages/electron/src/main/modules/BacktraceMainElectronModule.ts
  packages/electron/src/main/modules/IpcAttachment.ts
  packages/electron/src/renderer/ipc/WritableIpcStream.ts
  packages/electron/src/renderer/modules/IpcReportSubmission.ts
  packages/electron/src/renderer/modules/IpcSummedMetricsQueue.ts
  packages/nestjs/package.json
  packages/node/package.json
  packages/node/src/BacktraceNodeRequestHandler.ts
  packages/node/src/attachment/BacktraceBufferAttachment.ts
  packages/node/src/attachment/BacktraceFileAttachment.ts
  packages/node/tests/_mocks/fileSystem.ts
  packages/react-native/package.json
  packages/react-native/src/attributes/NativeAttributeProvider.ts
  packages/react-native/src/handlers/UnhandledExceptionHandler.ts
  packages/react-native/src/handlers/android/AndroidUnhandledException.ts
  packages/react/package.json
  packages/sdk-core/package.json
  packages/sdk-core/src/common/abortInterfaces.ts
  packages/sdk-core/src/dataStructures/OverwritingArrayIterator.ts
  packages/sdk-core/src/model/attachment/BacktraceStringAttachment.ts
  packages/sdk-core/src/model/attachment/BacktraceUint8ArrayAttachment.ts
  packages/sdk-core/src/model/data/BacktraceSubmissionResult.ts
  packages/sdk-core/src/model/http/BacktraceReportSubmission.ts
  packages/sdk-core/src/modules/attribute/FileAttributeManager.ts
  packages/sdk-core/src/modules/database/BacktraceDatabaseFileRecord.ts
  packages/sdk-core/src/modules/database/BacktraceDatabaseFileStorageProvider.ts
  packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
  packages/sdk-core/tests/_mocks/fileSystem.ts
  scripts/gitRelease.ts
  scripts/release.ts
  scripts/syncVersions.ts
  tools/cli/package.json
  tools/cli/src/sourcemaps/process.ts
  tools/cli/src/sourcemaps/run.ts
  tools/cli/src/sourcemaps/upload.ts
  tools/cli/tests/_helpers/common.ts
  tools/cli/tests/_helpers/matchers.ts
  tools/cli/tests/sourcemaps/add-sources.spec.ts
  tools/cli/tests/sourcemaps/process.spec.ts
  tools/cli/tests/sourcemaps/run.spec.ts
  tools/cli/tests/sourcemaps/upload.spec.ts
  tools/rollup-plugin/package.json
  tools/sourcemap-tools/package.json
  tools/sourcemap-tools/src/SymbolUploader.ts
  tools/vite-plugin/package.json
  tools/webpack-plugin/package.json
Labels: enhancement

#249 Include windows in CICD pipeline. Use @v4
  .github/workflows/test.yml
  .prettierrc.json
  examples/sdk/node/package.json
  package-lock.json
  package.json
  packages/browser/package.json
  packages/electron/package.json
  packages/electron/src/main/attributes/WindowAttributeProvider.ts
  packages/electron/src/main/ipc/ReadableIpcStream.ts
  packages/electron/src/main/modules/BacktraceMainElectronModule.ts
  packages/electron/src/main/modules/IpcAttachment.ts
  packages/electron/src/renderer/ipc/WritableIpcStream.ts
  packages/electron/src/renderer/modules/IpcReportSubmission.ts
  packages/electron/src/renderer/modules/IpcSummedMetricsQueue.ts
  packages/nestjs/package.json
  packages/node/package.json
  packages/node/src/BacktraceNodeRequestHandler.ts
  packages/node/src/attachment/BacktraceBufferAttachment.ts
  packages/node/src/attachment/BacktraceFileAttachment.ts
  packages/node/tests/_mocks/fileSystem.ts
  packages/react-native/package.json
  packages/react-native/src/attributes/NativeAttributeProvider.ts
  packages/react-native/src/handlers/UnhandledExceptionHandler.ts
  packages/react-native/src/handlers/android/AndroidUnhandledException.ts
  packages/react/package.json
  packages/sdk-core/package.json
  packages/sdk-core/src/common/abortInterfaces.ts
  packages/sdk-core/src/dataStructures/OverwritingArrayIterator.ts
  packages/sdk-core/src/model/attachment/BacktraceStringAttachment.ts
  packages/sdk-core/src/model/attachment/BacktraceUint8ArrayAttachment.ts
  packages/sdk-core/src/model/data/BacktraceSubmissionResult.ts
  packages/sdk-core/src/model/http/BacktraceReportSubmission.ts
  packages/sdk-core/src/modules/attribute/FileAttributeManager.ts
  packages/sdk-core/src/modules/database/BacktraceDatabaseFileRecord.ts
  packages/sdk-core/src/modules/database/BacktraceDatabaseFileStorageProvider.ts
  packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
  packages/sdk-core/tests/_mocks/fileSystem.ts
  scripts/gitRelease.ts
  scripts/release.ts
  scripts/syncVersions.ts
  tools/cli/package.json
  tools/cli/src/sourcemaps/process.ts
  tools/cli/src/sourcemaps/run.ts
  tools/cli/src/sourcemaps/upload.ts
  tools/cli/tests/_helpers/common.ts
  tools/cli/tests/_helpers/matchers.ts
  tools/cli/tests/sourcemaps/add-sources.spec.ts
  tools/cli/tests/sourcemaps/process.spec.ts
  tools/cli/tests/sourcemaps/run.spec.ts
  tools/cli/tests/sourcemaps/upload.spec.ts
  tools/rollup-plugin/package.json
  tools/sourcemap-tools/package.json
  tools/sourcemap-tools/src/SymbolUploader.ts
  tools/vite-plugin/package.json
  tools/webpack-plugin/package.json
Labels: enhancement

#251 node: version 0.3.2
  package-lock.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#255 electron: version 0.3.1
  package-lock.json
  packages/electron/CHANGELOG.md
  packages/electron/package.json
Labels: release

#256 session-replay: update rrweb and implement fixes
  examples/sdk/browser/package-lock.json
  examples/sdk/browser/package.json
  package-lock.json
  packages/session-replay/package.json
  packages/session-replay/src/BacktraceSessionRecorder.ts
  packages/session-replay/src/options.ts
Labels: enhancement

#257 session-replay: PII defaults
  examples/sdk/browser/index.html
  package-lock.json
  packages/session-replay/jest.config.js
  packages/session-replay/package.json
  packages/session-replay/src/BacktraceSessionRecorder.ts
  packages/session-replay/src/options.ts
  packages/session-replay/src/privacy/maskTextFn.ts
  packages/session-replay/tests/privacy/maskTextFn.spec.ts
Labels: enhancement

#258 session-replay: add README and update code docs
  packages/session-replay/README.md
  packages/session-replay/src/options.ts
Labels: documentation
