Repository backtrace-labs/backtrace-javascript, pull requests merged in 2024-10, with the labels that each got.

#290 sdk-core: use core client as event emitter, send reports from database via client
  packages/sdk-core/src/BacktraceCoreClient.ts
  packages/sdk-core/src/common/Events.ts
  packages/sdk-core/src/events/AttachmentEvents.ts
  packages/sdk-core/src/events/AttributeEvents.ts
  packages/sdk-core/src/events/ClientEvents.ts
  packages/sdk-core/src/modules/BacktraceModule.ts
  packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/src/modules/database/BacktraceDatabaseEvents.ts
  packages/sdk-core/src/modules/storage/SessionFiles.ts
  packages/sdk-core/tests/mocks/testHttpClient.ts
Labels: enhancement

#295 sdk-core: version 0.6.0
  package-lock.json
  packages/browser/package.json
  packages/node/package.json
  packages/react-native/package.json
  packages/react/package.json
  packages/sdk-core/CHANGELOG.md
  packages/sdk-core/package.json
  packages/session-replay/package.json
Labels: release

#297 node: version 0.6.0
  package-lock.json
  packages/electron/package.json
  packages/nestjs/package.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#298 electron: version 0.6.0
  package-lock.json
  packages/electron/CHANGELOG.md
  packages/electron/package.json
Labels: release

#293 nestjs: add exception filter and exception handler
  packages/nestjs/README.md
  packages/nestjs/src/backtrace.filter.ts
  packages/nestjs/src/backtrace.handler.ts
  packages/nestjs/src/backtrace.interceptor.ts
  packages/nestjs/src/backtrace.module.ts
  packages/nestjs/src/index.ts
  packages/nestjs/tests/backtrace.filter.e2e.spec.ts
  packages/nestjs/tests/backtrace.handler.spec.ts
  packages/nestjs/tests/backtrace.interceptor.e2e.spec.ts
  packages/nestjs/tests/backtrace.interceptor.spec.ts
Labels: enhancement

#299 nestjs: version 0.5.0
  package-lock.json
  packages/nestjs/CHANGELOG.md
  packages/nestjs/package.json
Labels: release

#303 node: fix invalid breadcrumb name in FileBreadcrumbsStorage
  packages/node/src/breadcrumbs/FileBreadcrumbsStorage.ts
  packages/node/tests/breadcrumbs/FileBreadcrumbsStorage.spec.ts
Labels: bug

#304 node: version 0.6.1
  package-lock.json
  packages/electron/package.json
  packages/nestjs/package.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#306 react-native: fix previous sessions not being cleared
  packages/react-native/android/src/main/java/backtrace/library/BacktraceDirectoryProvider.java
  packages/react-native/src/BacktraceClient.ts
Labels: bug

#308 react-native: fix invalid RN object returned from iOS BacktraceReactNative.initialize function
  packages/react-native/ios/BacktraceReactNative.mm
Labels: bug

#307 react-native: remove invalid imports from iOS headers
  packages/react-native/ios/BacktraceApplicationAttributeProvider.h
  packages/react-native/ios/BacktraceCpuAttributeProvider.h
  packages/react-native/ios/BacktraceDeviceAttributeProvider.h
  packages/react-native/ios/BacktraceDirectoryProvider.h
  packages/react-native/ios/BacktraceFileSystemProvider.h
  packages/react-native/ios/BacktraceMemoryUsageAttributeProvider.h
  packages/react-native/ios/BacktraceReactNative.h
  packages/react-native/ios/BacktraceSystemAttributeProvider.h
  packages/react-native/ios/StreamWriter.h
Labels: bug

#309 nestjs: fix skipIfClientUndefined not working in BacktraceModule
  packages/nestjs/src/backtrace.module.ts
  packages/nestjs/tests/backtrace.handler.spec.ts
  packages/nestjs/tests/backtrace.module.spec.ts
Labels: bug

#310 nestjs: version 0.5.1
  package-lock.json
  packages/nestjs/CHANGELOG.md
  packages/nestjs/package.json
Labels: release

#311 electron: change default electron version to the latest
  packages/electron/package.json
Labels: enhancement

#312 electron: version 0.6.1
  package-lock.json
  packages/electron/CHANGELOG.md
  packages/electron/package.json
Labels: enhancement
