Repository backtrace-labs/backtrace-javascript, pull requests merged in 2024-07, with the labels that each got.

#259 cli: add retry to removing files after test
  tools/cli/tests/_helpers/testFiles.ts
Labels: bug

#260 Add support for error.type for electron crashes
  examples/sdk/electron/package-lock.json
  packages/electron/src/main/modules/BacktraceMainElectronModule.ts
Labels: enhancement

#261 session-replay: version 0.1.0
  package-lock.json
  packages/session-replay/CHANGELOG.md
  packages/session-replay/package.json
Labels: release
