Repository backtrace-labs/backtrace-javascript, pull requests merged in 2024-09, with the labels that each got.

#272 session-replay: use ESM modules
  package-lock.json
  packages/session-replay/jest.config.js
  packages/session-replay/jest.config.mjs
  packages/session-replay/jest.setup.mjs
  packages/session-replay/package.json
  packages/session-replay/rollup.config.mjs
  packages/session-replay/src/BacktraceSessionReplayModule.ts
  packages/session-replay/tsconfig.build.json
  packages/session-replay/tsconfig.json
  packages/session-replay/webpack.config.js
Labels: bug, enhancement

#278 session-replay: version 0.1.1
  package-lock.json
  packages/session-replay/CHANGELOG.md
  packages/session-replay/package.json
Labels: release

#266 sdk-core: use ESM modules
  package-lock.json
  packages/browser/src/BacktraceBrowserSessionProvider.ts
  packages/browser/src/attributes/WebsiteAttributeProvider.ts
  packages/browser/tests/metrics/persistentSessionProviderTests.spec.ts
  packages/sdk-core/jest.config.js
  packages/sdk-core/jest.config.mjs
  packages/sdk-core/jest.setup.mjs
  packages/sdk-core/package.json
  packages/sdk-core/rollup.config.mjs
  packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
  packages/sdk-core/tests/database/databaseContextMemoryStorageTests.spec.ts
  packages/sdk-core/tests/database/databaseContextValidationTests.spec.ts
  packages/sdk-core/tests/database/databaseRecordBatchTests.spec.ts
  packages/sdk-core/tests/database/databaseSendTests.spec.ts
  packages/sdk-core/tests/database/databaseStorageFlowTests.spec.ts
  packages/sdk-core/tsconfig.build.json
  packages/sdk-core/tsconfig.json
Labels: enhancement

#268 browser: use ESM modules
  package-lock.json
  packages/browser/jest.config.js
  packages/browser/jest.config.mjs
  packages/browser/jest.setup.mjs
  packages/browser/package.json
  packages/browser/rollup.config.mjs
  packages/browser/src/agentDefinition.ts
  packages/browser/tests/redux/backtraceReduxMiddlewareTests.spec.ts
  packages/browser/tsconfig.build.json
  packages/browser/tsconfig.json
  packages/browser/webpack.config.js
Labels: enhancement

#269 react: use ESM modules
  package-lock.json
  packages/react/jest.config.js
  packages/react/jest.config.mjs
  packages/react/jest.setup.mjs
  packages/react/package.json
  packages/react/rollup.config.mjs
  packages/react/src/ErrorBoundary.tsx
  packages/react/src/agentDefinition.ts
  packages/react/tsconfig.build.json
  packages/react/tsconfig.json
  packages/react/webpack.config.js
Labels: enhancement

#267 node: use ESM modules
  package-lock.json
  packages/node/jest.config.js
  packages/node/jest.config.mjs
  packages/node/jest.setup.mjs
  packages/node/package.json
  packages/node/rollup.config.mjs
  packages/node/src/agentDefinition.ts
  packages/node/src/attributes/ApplicationInformationAttributeProvider.ts
  packages/node/tests/attributes/applicationInformationAttributeProviderTests.spec.ts
  packages/node/tests/client/clientTests.spec.ts
  packages/node/tests/client/disposeTests.spec.ts
  packages/node/tests/common/alternatingFile.spec.ts
  packages/node/tsconfig.build.json
  packages/node/tsconfig.json
  packages/node/webpack.config.js
Labels: enhancement

#270 electron: use ESM modules
  package-lock.json
  packages/electron/jest.config.js
  packages/electron/jest.setup.js
  packages/electron/package.json
  packages/electron/rollup.config.mjs
  packages/electron/tsconfig.build.json
  packages/electron/tsconfig.json
  packages/electron/tsconfig.main.json
  packages/electron/tsconfig.renderer.json
  packages/electron/webpack.config.js
Labels: enhancement

#265 sdk-core, browser, react-native: fix abort event not being removed from signal
  packages/browser/src/BacktraceBrowserRequestHandler.ts
  packages/react-native/src/ReactNativeRequestHandler.ts
  packages/sdk-core/src/common/AbortController.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/src/modules/metrics/MetricsSubmissionQueue.ts
  packages/session-replay/package.json
Labels: bug

#271 nestjs: use ESM modules
  package-lock.json
  packages/nestjs/jest.config.js
  packages/nestjs/jest.config.mjs
  packages/nestjs/jest.setup.mjs
  packages/nestjs/package.json
  packages/nestjs/rollup.config.mjs
  packages/nestjs/src/index.ts
  packages/nestjs/tests/backtrace.interceptor.spec.ts
  packages/nestjs/tests/backtrace.module.spec.ts
  packages/nestjs/tests/e2e.spec.ts
  packages/nestjs/tsconfig.build.json
  packages/nestjs/tsconfig.json
  packages/nestjs/webpack.config.js
Labels: enhancement

#280 sdk-core: version 0.5.0
  package-lock.json
  packages/browser/package.json
  packages/node/package.json
  packages/react-native/package.json
  packages/react/package.json
  packages/sdk-core/CHANGELOG.md
  packages/sdk-core/package.json
  packages/session-replay/package.json
Labels: release

#281 browser: version 0.4.0
  package-lock.json
  packages/browser/CHANGELOG.md
  packages/browser/package.json
  packages/react/package.json
Labels: release

#282 react: version 0.4.0
  package-lock.json
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: release

#284 session-replay: version 0.2.0
  package-lock.json
  packages/session-replay/CHANGELOG.md
  packages/session-replay/package.json
Labels: release

#285 node: version 0.5.0
  package-lock.json
  packages/electron/package.json
  packages/nestjs/package.json
  packages/node/CHANGELOG.md
  packages/node/package.json
Labels: release

#286 electron: version 0.5.0
  package-lock.json
  packages/electron/CHANGELOG.md
  packages/electron/package.json
Labels: release

#288 nestjs: include tslib in code instead of externalizing it
  packages/nestjs/rollup.config.mjs
Labels: bug

#289 nestjs: version 0.4.1
  package-lock.json
  packages/nestjs/CHANGELOG.md
  packages/nestjs/package.json
Labels: release

#291 sdk-core: unref setinterval
  packages/sdk-core/src/common/intervalHelper.ts
  packages/sdk-core/src/modules/database/BacktraceDatabase.ts
  packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
Labels: bug

#231 electron: reduce breadcrumb size
  packages/electron/src/main/modules/BacktraceMainElectronModule.ts
  packages/electron/src/renderer/addBacktraceElectron.ts
  packages/electron/src/renderer/modules/IpcBreadcrumbsStorage.ts
Labels: enhancement
