Repository backtrace-labs/backtrace-javascript, pull requests merged in 2025-01, with the labels that each got.

#332 sourcemap-tools: add processSource to SourceProcessor
  tools/sourcemap-tools/src/SourceProcessor.ts
Labels: enhancement

#333 react-native: simplify source map processing flow
  examples/sdk/reactNative/README.md
  examples/sdk/reactNative/android-sourcemap.sh
  examples/sdk/reactNative/android/app/build.gradle
  examples/sdk/reactNative/ios-hermesc.sh
  examples/sdk/reactNative/ios-sourcemaps.sh
  examples/sdk/reactNative/ios/reactNative.xcodeproj/project.pbxproj
  examples/sdk/reactNative/metro.config.js
  examples/sdk/reactNative/package-lock.json
  examples/sdk/reactNative/package.json
  packages/react-native/android/upload-sourcemaps.gradle
  packages/react-native/scripts/addDebugIdToSourceMap.js
  packages/react-native/scripts/ios-sourcemap-upload.sh
  packages/react-native/scripts/processSourceMap.js
Labels: enhancement

#321 react-native: version 0.2.0
  package-lock.json
  packages/react-native/CHANGELOG.md
  packages/react-native/package.json
Labels: release

#334 sourcemap-tools: version 0.2.4
  package-lock.json
  tools/cli/package.json
  tools/rollup-plugin/package.json
  tools/sourcemap-tools/CHANGELOG.md
  tools/sourcemap-tools/package.json
  tools/webpack-plugin/package.json
Labels: enhancement, release
